# generated by pl5:
#' @export 
pfs.best <- readRDS(system.file(  'fits', 'pl5.0-pfbest.rds', package = 'mpoxsmcam.app' ) )

#' @export 
MODELS <- c('B', 'B_IRD', 'B_IRD_PRD', 'B_PRD') 
#' @export 
BEST <- 'B_IRD_PRD'
#' @export 
BEST2 <- 'B_IRD_PRD2'
#' @export 
COUNTRIES2 <- c('ES', 'IE')
#' @export 
COUNTRIES <- c('NL', 'ES', 'IE')
#' @export 
CNTRY <- 'NL'

#' @export 
d <- read.csv( system.file( 'd0-odf1.csv' , package = 'mpoxsmcam.app') ) 
d$cases <- pmax(0, d$cases )

#' @export 
ds <- lapply( COUNTRIES , function(CNTRY)
	d[ d$ReportingCountry == CNTRY , ]
	)
names(ds) <- COUNTRIES

#' @export 
d2 <- read.csv( system.file(  'd0-odf2.csv', package = 'mpoxsmcam.app') ) 
#' @export 
dnl <- d2[ d2$ReportingCountry == 'NL', ]
#' @export 
vd <- read.csv( system.file( 'd0-nl-vd2.csv', package  = 'mpoxsmcam.app' ) )


#' @export 
IUW <- c( 'Iagg', 'Uagg', 'Wagg' )

#' @export 
fits <- list() 
fits[[BEST]] <- lapply( COUNTRIES2, function(x){
		readRDS( system.file( 'fits', glue::glue('./ex50b-{BEST2}-{x}.rds'), package='mpoxsmcam.app') )$mf 
})
names( fits[[BEST]] ) <- COUNTRIES2
# add NL separately 
fits[[BEST]][[ CNTRY ]] <- readRDS(  system.file('fits', glue::glue( './ex50-{BEST}-{CNTRY}.rds'), package='mpoxsmcam.app') )$mf 


#' @export 
psumdf <- data.frame(
	  parameter	= c("gammae"	, "gammai"	, "alpha"	, "waningnat"	, "waningvac"	, "turnover"	, "omega"	, "sigma_foi"	, "N"		, "r"		, "rdrift"	, "iota0"	, "iota1"	, "iota2"	, "iota3"	, "sampf"	, "vaccstrat"	, "ve1"		, "ve"		, "initv")
	, alias		= c("$\\gamma_e$", "$\\gamma_i$"	, "$\\alpha$"	, "$\\omega_{nat}$"	, "$\\omega_{vac}$"	, "$\\mu$"	, "$\\omega$"	, "$\\sigma_{foi}$"	, "$N$"		, "$r$"		, "$\\sigma_{drift}$"	, "$\\iota_0$"	, "$\\iota_1$"	, "$\\iota_2$"	, "$\\iota_3$"	, "$\\rho$"	, "$\\mathrm{vaccstrat}$"	, "$v_1$"		, "$v_2$"		, "$v_{init}$")
	, default	= c(1/8		, 1/4		, .15		, 1/(20*365)	, 1/(20*365)	, 1/(40*365)	, 1/(2*365)	, 3.0		, 260e3		, 1		, .05		, .01		, 100		, 1		, .05		, .33		, 1		, .36		, .66		, .20)
	, Estimated	= c(FALSE	, FALSE		, TRUE		, FALSE		, FALSE		, FALSE		, TRUE		, TRUE		, FALSE		, TRUE		, TRUE		, TRUE		, FALSE		, FALSE		, FALSE		, FALSE		, FALSE		, FALSE		, FALSE		, FALSE)
	, NL		= rep(0, 20)
	, ES		= rep(0, 20)
	, IE		= rep(0, 20)
	, Elasticity	= c(FALSE	, TRUE		, TRUE		, TRUE		, TRUE		, TRUE		, TRUE		, FALSE		, TRUE		, TRUE		, TRUE		, TRUE		, TRUE		, TRUE		, TRUE		, TRUE		, FALSE		, TRUE		, TRUE		, TRUE)
	, Importance	= c(FALSE	, FALSE		, FALSE		, TRUE		, TRUE		, TRUE		, TRUE		, TRUE		, FALSE		, FALSE		, TRUE		, FALSE		, FALSE		, FALSE		, FALSE		, FALSE		, FALSE		, FALSE		, FALSE		, TRUE)
	, Sensitivity	= c(TRUE	, TRUE		, FALSE		, FALSE		, FALSE		, TRUE		, FALSE		, FALSE		, TRUE		, FALSE		, FALSE		, FALSE		, TRUE		, TRUE		, TRUE		, TRUE		, FALSE		, TRUE		, TRUE		, TRUE)
	, stringsAsFactors = FALSE
)

.ptoR <- function(P)
{
	tryCatch( 
		with(as.list(P), 
			r*(1/gammai)*((alpha+1)/(alpha)) 
		)
			, error = function(e) NA 
	)	

}

#' @export 
.fmll <- function( mf, P2 = NULL , Np = 1e4, nrep = 5, ncpu = 8)
{
	if ( is.null( P2 ) )
		P2 <- coef(mf)
	cl <- makeCluster(ncpu)
	registerDoParallel(cl)
	lls <- foreach(i=1:nrep, .combine=rbind, .packages='pomp') %dopar% {
		o <- pfilter( mf, params = P2, Np = Np) 
		logLik( o ) 
	}
	stopCluster(cl)
	print( sort( lls ))
	logmeanexp( lls, se = TRUE )
}

