# generated by pl5:
pfs.best <- readRDS(system.file( 'inst', 'fits', 'pl5.0-pfbest.rds', package = 'mpoxsmcam.app' ) )

read.csv( system.file('inst', 'd0-odf1.csv' , package = 'mpoxsmcam.app') ) -> d
d$cases <- pmax(0, d$cases )
ds <- lapply( COUNTRIES , function(CNTRY)
	d[ d$ReportingCountry == CNTRY , ]
	)
names(ds) <- COUNTRIES

d2 <- read.csv( system.file( 'inst', 'd0-odf2.csv', package = 'mpoxsmcam.app') 
dnl <- d2[ d2$ReportingCountry == 'NL', ]
vd <- read.csv( system.file('inst', 'd0-nl-vd2.csv', package  = 'mpoxsmcam.app' ) )


MODELS <- c('B', 'B_IRD', 'B_IRD_PRD', 'B_PRD') 
BEST <- 'B_IRD_PRD'
BEST2 <- 'B_IRD_PRD2'
COUNTRIES2 <- c('ES', 'IE')
COUNTRIES <- c('NL', 'ES', 'IE')
CNTRY <- 'NL'

IUW <- c( 'Iagg', 'Uagg', 'Wagg' )

fits <- list() 
fits[[BEST]] <- lapply( COUNTRIES2, function(x){
		readRDS( system.file('inst', 'fits', glue::glue('./ex50b-{BEST2}-{x}.rds'), package='mpoxsmcam.app') )$mf 
})
names( fits[[BEST]] ) <- COUNTRIES2
# add NL separately 
fits[[BEST]][[ CNTRY ]] <- readRDS(  system.file('inst', 'fits', glue::glue( './ex50-{BEST}-{CNTRY}.rds'), package='mpoxsmcam.app') )$mf 


psumdf <- data.frame(
	  parameter	= c("gammae"	, "gammai"	, "alpha"	, "waningnat"	, "waningvac"	, "turnover"	, "omega"	, "sigma_foi"	, "N"		, "r"		, "rdrift"	, "iota0"	, "iota1"	, "iota2"	, "iota3"	, "sampf"	, "vaccstrat"	, "ve1"		, "ve"		, "initv")
	, default	= c(1/8		, 1/4		, "a"		, 1/(20*365)	, 1/(20*365)	, 1/(40*365)	, 1/(2*365)	, 3.0		, 260e3		, ".r"		, .05		, .01		, 100		, 1		, .05		, .33		, 1		, .36		, .66		, .20)
	, Estimated	= c(F		, F		, TRUE		, F		, F		, F		, TRUE		, TRUE		, F		, TRUE		, TRUE		, TRUE		, F		, F		, F		, F		, F		, F		, F		, F)
	, NL		= rep(0, 20)
	, ES		= rep(0, 20)
	, IE		= rep(0, 20)
	, Elasticity	= c(TRUE	, TRUE		, TRUE		, TRUE		, TRUE		, TRUE		, TRUE		, TRUE		, TRUE		, TRUE		, TRUE		, TRUE		, TRUE		, TRUE		, TRUE		, TRUE		, FALSE		, TRUE		, TRUE		, TRUE)
	, Importance	= c(FALSE	, FALSE		, FALSE		, TRUE		, TRUE		, TRUE		, TRUE		, TRUE		, FALSE		, FALSE		, TRUE		, FALSE		, FALSE		, FALSE		, FALSE		, FALSE		, FALSE		, FALSE		, FALSE		, TRUE)
	, Sensitivity	= c(TRUE	, TRUE		, FALSE		, FALSE		, FALSE		, TRUE		, FALSE		, FALSE		, TRUE		, FALSE		, FALSE		, FALSE		, TRUE		, TRUE		, TRUE		, TRUE		, FALSE		, TRUE		, TRUE		, TRUE)
	, stringsAsFactors = FALSE
)

.ptoR <- function(P)
{
	tryCatch( 
		with(as.list(P), 
			r*(1/gammai)*((alpha+1)/(alpha)) 
		)
			, error = function(e) NA 
	)	

}

.fmll <- function( mf, Np = 1e4, nrep = 10, ncpu = 8)
{
	P2 <- coef(mf) 
	cl <- makeCluster(ncpu)
	registerDoParallel(cl)
	lls <- foreach(i=1:nrep, .combine=rbind, .packages='pomp') %dopar% {
		o <- pfilter( mf, params = P2, Np = Np) 
		logLik( o ) 
	}
	stopCluster(cl)
	print( sort( lls ))
	logmeanexp( lls, se = TRUE )
}

